package worktree

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// HookScripts holds embedded hook script content for deployment.
type HookScripts struct {
	PathGuard        []byte
	BashFirewall     []byte
	PwshFirewall     []byte // pwsh-firewall.sh — PowerShell-tool counterpart of BashFirewall
	GitGuard         []byte
	EnvWrapper       []byte // zpit-env.cmd — sets ZPIT_AGENT=1 for Windows agent launches (cmd)
	EnvWrapperPS1    []byte // zpit-env.ps1 — sets ZPIT_AGENT=1 for Windows agent launches (pwsh/powershell)
	ExitWrapper      []byte // zpit-exit.cmd — clean exit for Windows non-agent launches (cmd)
	ExitWrapperPS1   []byte // zpit-exit.ps1 — clean exit for Windows non-agent launches (pwsh/powershell)
	NotifyPermission []byte // Notification hook — writes permission signal for Zpit TUI
	WorktreeCreate   []byte // WorktreeCreate hook — forks child worktree from orchestrator HEAD for [P] parallel subagents
}

// settingsTemplate is the canonical hook configuration written into every
// zpit-managed project and worktree. Non-agent Claude Code sessions are
// unaffected because each hook script short-circuits when ZPIT_AGENT is
// unset.
const settingsTemplate = `{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/path-guard.sh"
          }
        ]
      },
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/bash-firewall.sh"
          },
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/git-guard.sh"
          }
        ]
      },
      {
        "matcher": "PowerShell",
        "hooks": [
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/pwsh-firewall.sh"
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/notify-permission.sh"
          }
        ]
      }
    ],
    "WorktreeCreate": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/worktree-create.sh",
            "timeout": 30
          }
        ]
      }
    ]
  }
}`

// ZpitDeployedDirs lists the .claude/ subdirectories fully managed by Zpit.
var ZpitDeployedDirs = []string{"agents", "docs", "hooks"}

// ZpitDeployedFiles lists project-root files generated by Zpit.
var ZpitDeployedFiles = []string{".mcp.json"}

// zpitIgnoreRules are .gitignore patterns for Zpit auto-deployed files.
// Derived from ZpitDeployedDirs and ZpitDeployedFiles to stay in sync.
//
// Policy: everything under .claude/ that zpit writes is gitignored,
// including settings.json itself. That file is merged by mergeSettingsHooks
// on every agent launch, and committing it creates a latent fresh-clone
// bug because the hook commands it references
// (.claude/hooks/*.sh) live in gitignored directories and don't exist
// until zpit has deployed at least once. Team-shared user config (plugin
// enablement, custom CC keys) should live in a hand-maintained file
// outside zpit's deployment scope, e.g. a project-root CLAUDE.md note.
// Per-machine user config goes in .claude/settings.local.json — that file
// is Claude Code's conventional local-override slot and is gitignored by
// Claude Code's own init/defaults on most projects; zpit does not add it
// here to avoid polluting user-owned .gitignore on every launch.
var zpitIgnoreRules = func() []string {
	var rules []string
	for _, d := range ZpitDeployedDirs {
		rules = append(rules, ".claude/"+d+"/")
	}
	rules = append(rules, ".claude/settings.json")
	rules = append(rules, ZpitDeployedFiles...)
	// .zpit-children/ holds ephemeral per-subagent worktrees created by the
	// WorktreeCreate hook during [P] batches. Cleaned up by the orchestrator
	// post-cherry-pick but always gitignored so in-flight or abandoned
	// children never leak into a PR.
	rules = append(rules, ".zpit-children/")
	return rules
}()

// ensureFileRules appends missing rules to a file, using "# Zpit auto-deploy" as header.
// Silently ignores errors (best-effort).
func ensureFileRules(filePath string, rules []string) {
	content, _ := os.ReadFile(filePath)
	existing := make(map[string]bool)
	for _, line := range strings.Split(string(content), "\n") {
		existing[strings.TrimSpace(line)] = true
	}

	var missing []string
	for _, rule := range rules {
		if !existing[rule] {
			missing = append(missing, rule)
		}
	}
	if len(missing) == 0 {
		return
	}

	var buf strings.Builder
	if len(content) > 0 && !strings.HasSuffix(string(content), "\n") {
		buf.WriteByte('\n')
	}
	if !existing["# Zpit auto-deploy"] {
		buf.WriteString("\n# Zpit auto-deploy\n")
	}
	for _, rule := range missing {
		buf.WriteString(rule)
		buf.WriteByte('\n')
	}

	f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	f.WriteString(buf.String())
}

// EnsureGitignore appends missing Zpit gitignore rules to a project's .gitignore.
func EnsureGitignore(projectPath string) {
	ensureFileRules(filepath.Join(projectPath, ".gitignore"), zpitIgnoreRules)
}

// DeployHooksToProject writes hook scripts to .claude/hooks/ and merges hook config
// into the existing .claude/settings.json (preserving other keys like enabledPlugins).
func DeployHooksToProject(targetPath string, scripts HookScripts) error {
	if err := deployHookScripts(targetPath, scripts); err != nil {
		return fmt.Errorf("deploying hook scripts: %w", err)
	}
	return mergeSettingsHooks(targetPath)
}

// DeployHooksToWorktree writes hook scripts to .claude/hooks/ and writes BOTH
// .claude/settings.json and .claude/settings.local.json into the worktree.
//
// Why both: Claude Code resolves project settings via
// getSettingsRootPathForSource() (src/utils/settings/settings.ts:244-253),
// which uses the process CWD. Linked git worktrees do NOT inherit settings
// from the main repo — without an explicit file in the worktree, every hook
// (path-guard, bash-firewall, pwsh-firewall, git-guard, notify-permission,
// worktree-create) is silently disabled inside that worktree. Writing
// settings.json covers the project layer; settings.local.json covers the
// local-override layer so a user-side override file does not displace the
// zpit-managed hooks.
func DeployHooksToWorktree(targetPath string, scripts HookScripts) error {
	if err := deployHookScripts(targetPath, scripts); err != nil {
		return fmt.Errorf("deploying hook scripts: %w", err)
	}
	if err := writeSettings(targetPath, settingsTemplate); err != nil {
		return err
	}
	return writeSettingsLocal(targetPath, settingsTemplate)
}

// writeSettings writes .claude/settings.json with the given content,
// no-op if the file already matches.
func writeSettings(worktreePath, content string) error {
	return writeClaudeJSON(worktreePath, "settings.json", content)
}

// writeSettingsLocal writes .claude/settings.local.json with the given content,
// no-op if the file already matches.
func writeSettingsLocal(worktreePath, content string) error {
	return writeClaudeJSON(worktreePath, "settings.local.json", content)
}

func writeClaudeJSON(worktreePath, filename, content string) error {
	claudeDir := filepath.Join(worktreePath, ".claude")
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return fmt.Errorf("creating .claude dir: %w", err)
	}
	path := filepath.Join(claudeDir, filename)
	existing, _ := os.ReadFile(path)
	if bytes.Equal(existing, []byte(content)) {
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", filename, err)
	}
	return nil
}

// deployHookScripts writes hook scripts and env wrapper to .claude/hooks/.
func deployHookScripts(targetPath string, scripts HookScripts) error {
	hooksDir := filepath.Join(targetPath, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("creating hooks dir: %w", err)
	}
	files := map[string][]byte{
		"path-guard.sh":        scripts.PathGuard,
		"bash-firewall.sh":     scripts.BashFirewall,
		"pwsh-firewall.sh":     scripts.PwshFirewall,
		"git-guard.sh":         scripts.GitGuard,
		"zpit-env.cmd":         scripts.EnvWrapper,
		"zpit-env.ps1":         scripts.EnvWrapperPS1,
		"zpit-exit.cmd":        scripts.ExitWrapper,
		"zpit-exit.ps1":        scripts.ExitWrapperPS1,
		"notify-permission.sh": scripts.NotifyPermission,
		"worktree-create.sh":   scripts.WorktreeCreate,
	}
	for name, content := range files {
		p := filepath.Join(hooksDir, name)
		if err := os.WriteFile(p, content, 0o755); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}

// mergeSettingsHooks reads existing .claude/settings.json, sets the "hooks" key
// from settingsTemplate, and writes back. Preserves all other existing keys
// (enabledPlugins, etc.) so user-managed settings survive zpit redeploys.
func mergeSettingsHooks(targetPath string) error {
	claudeDir := filepath.Join(targetPath, ".claude")
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return fmt.Errorf("creating .claude dir: %w", err)
	}
	settingsPath := filepath.Join(claudeDir, "settings.json")

	// Read existing settings or start fresh.
	var settings map[string]interface{}
	data, err := os.ReadFile(settingsPath)
	if err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			settings = make(map[string]interface{})
		}
	} else {
		settings = make(map[string]interface{})
	}

	// Extract "hooks" value from the template.
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(settingsTemplate), &parsed); err != nil {
		return fmt.Errorf("parsing hook template: %w", err)
	}
	settings["hooks"] = parsed["hooks"]

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling settings: %w", err)
	}
	newData := append(out, '\n')
	if bytes.Equal(data, newData) {
		return nil
	}
	return os.WriteFile(settingsPath, newData, 0o644)
}

// CleanSettingsHooks removes the Zpit-injected "hooks" key from .claude/settings.json.
// If the file becomes an empty object after removal, it is deleted.
// Returns true if any change was made.
func CleanSettingsHooks(projectPath string) bool {
	settingsPath := filepath.Join(projectPath, ".claude", "settings.json")
	data, err := os.ReadFile(settingsPath)
	if err != nil {
		return false
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		return false
	}
	if _, ok := settings["hooks"]; !ok {
		return false
	}

	delete(settings, "hooks")

	if len(settings) == 0 {
		os.Remove(settingsPath)
		return true
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return false
	}
	os.WriteFile(settingsPath, append(out, '\n'), 0o644)
	return true
}
