package worktree

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// HookScripts holds embedded hook script content for deployment.
type HookScripts struct {
	PathGuard        []byte
	BashFirewall     []byte
	GitGuard         []byte
	EnvWrapper       []byte // zpit-env.cmd — sets ZPIT_AGENT=1 for Windows agent launches (cmd)
	EnvWrapperPS1    []byte // zpit-env.ps1 — sets ZPIT_AGENT=1 for Windows agent launches (pwsh/powershell)
	ExitWrapper      []byte // zpit-exit.cmd — clean exit for Windows non-agent launches (cmd)
	ExitWrapperPS1   []byte // zpit-exit.ps1 — clean exit for Windows non-agent launches (pwsh/powershell)
	NotifyPermission []byte // Notification hook — writes permission signal for Zpit TUI
	WorktreeCreate   []byte // WorktreeCreate hook — forks child worktree from orchestrator HEAD for [P] teammates
}

// Hook configuration JSON for each mode.

const settingsStrict = `{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/path-guard.sh"
          }
        ]
      },
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/bash-firewall.sh"
          },
          {
            "type": "command",
            "command": ".claude/hooks/git-guard.sh"
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/notify-permission.sh"
          }
        ]
      }
    ],
    "WorktreeCreate": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/worktree-create.sh",
            "timeout": 30
          }
        ]
      }
    ]
  }
}`

const settingsStandard = `{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/path-guard.sh"
          }
        ]
      },
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/git-guard.sh"
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/notify-permission.sh"
          }
        ]
      }
    ],
    "WorktreeCreate": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/worktree-create.sh",
            "timeout": 30
          }
        ]
      }
    ]
  }
}`

const settingsRelaxed = `{
  "hooks": {
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/git-guard.sh"
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/notify-permission.sh"
          }
        ]
      }
    ],
    "WorktreeCreate": [
      {
        "matcher": "*",
        "hooks": [
          {
            "type": "command",
            "command": ".claude/hooks/worktree-create.sh",
            "timeout": 30
          }
        ]
      }
    ]
  }
}`

// hookModeTemplates maps valid hook_mode values to their JSON template.
var hookModeTemplates = map[string]string{
	"strict":   settingsStrict,
	"standard": settingsStandard,
	"relaxed":  settingsRelaxed,
}

// validateHookMode returns an error if hookMode is not a recognized value.
func validateHookMode(hookMode string) error {
	if _, ok := hookModeTemplates[hookMode]; !ok {
		return fmt.Errorf("unknown hook_mode: %s (expected strict|standard|relaxed)", hookMode)
	}
	return nil
}

// ZpitDeployedDirs lists the .claude/ subdirectories fully managed by Zpit.
var ZpitDeployedDirs = []string{"agents", "docs", "hooks"}

// ZpitDeployedFiles lists project-root files generated by Zpit.
var ZpitDeployedFiles = []string{".mcp.json"}

// zpitIgnoreRules are .gitignore patterns for Zpit auto-deployed files.
// Derived from ZpitDeployedDirs and ZpitDeployedFiles to stay in sync.
//
// Policy: everything under .claude/ that zpit writes is gitignored,
// including settings.json itself. That file is merged by mergeSettingsHooks
// on every agent launch, and committing it creates a latent fresh-clone
// bug because the hook commands it references
// (.claude/hooks/*.sh) live in gitignored directories and don't exist
// until zpit has deployed at least once. Team-shared user config (plugin
// enablement, custom CC keys) should live in a hand-maintained file
// outside zpit's deployment scope, e.g. a project-root CLAUDE.md note.
// Per-machine user config goes in .claude/settings.local.json (also
// gitignored here for the same reason).
var zpitIgnoreRules = func() []string {
	var rules []string
	for _, d := range ZpitDeployedDirs {
		rules = append(rules, ".claude/"+d+"/")
	}
	rules = append(rules, ".claude/settings.json")
	rules = append(rules, ".claude/settings.local.json")
	rules = append(rules, ZpitDeployedFiles...)
	// .zpit-children/ holds ephemeral per-teammate worktrees created by the
	// WorktreeCreate hook during [P] batches. Cleaned up by the orchestrator
	// post-cherry-pick but always gitignored so in-flight or abandoned
	// children never leak into a PR.
	rules = append(rules, ".zpit-children/")
	return rules
}()

// ensureFileRules appends missing rules to a file, using "# Zpit auto-deploy" as header.
// Silently ignores errors (best-effort).
func ensureFileRules(filePath string, rules []string) {
	content, _ := os.ReadFile(filePath)
	existing := make(map[string]bool)
	for _, line := range strings.Split(string(content), "\n") {
		existing[strings.TrimSpace(line)] = true
	}

	var missing []string
	for _, rule := range rules {
		if !existing[rule] {
			missing = append(missing, rule)
		}
	}
	if len(missing) == 0 {
		return
	}

	var buf strings.Builder
	if len(content) > 0 && !strings.HasSuffix(string(content), "\n") {
		buf.WriteByte('\n')
	}
	if !existing["# Zpit auto-deploy"] {
		buf.WriteString("\n# Zpit auto-deploy\n")
	}
	for _, rule := range missing {
		buf.WriteString(rule)
		buf.WriteByte('\n')
	}

	f, err := os.OpenFile(filePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return
	}
	defer f.Close()
	f.WriteString(buf.String())
}

// EnsureGitignore appends missing Zpit gitignore rules to a project's .gitignore.
func EnsureGitignore(projectPath string) {
	ensureFileRules(filepath.Join(projectPath, ".gitignore"), zpitIgnoreRules)
}

// zpitGitattributesRules are .gitattributes rules for Zpit-managed files.
var zpitGitattributesRules = []string{
	".claude/settings.json text eol=lf",
}

// EnsureGitattributes appends missing Zpit gitattributes rules to a project's .gitattributes.
func EnsureGitattributes(projectPath string) {
	ensureFileRules(filepath.Join(projectPath, ".gitattributes"), zpitGitattributesRules)
}

// DeployHooksToProject writes hook scripts to .claude/hooks/ and merges hook config
// into the existing .claude/settings.json (preserving other keys like enabledPlugins).
func DeployHooksToProject(targetPath, hookMode string, scripts HookScripts) error {
	if err := validateHookMode(hookMode); err != nil {
		return err
	}
	if err := deployHookScripts(targetPath, scripts); err != nil {
		return fmt.Errorf("deploying hook scripts: %w", err)
	}
	return mergeSettingsHooks(targetPath, hookMode)
}

// DeployHooksToWorktree writes hook scripts to .claude/hooks/ and configures
// .claude/settings.local.json overlay based on hookMode.
// For "strict", no overlay is written (the worktree inherits the base settings.json).
func DeployHooksToWorktree(targetPath, hookMode string, scripts HookScripts) error {
	if err := validateHookMode(hookMode); err != nil {
		return err
	}
	if err := deployHookScripts(targetPath, scripts); err != nil {
		return fmt.Errorf("deploying hook scripts: %w", err)
	}
	return setupHookMode(targetPath, hookMode)
}

// setupHookMode configures .claude/settings.local.json in the worktree.
// For "strict", no overlay is written. hookMode is assumed already validated.
func setupHookMode(worktreePath, hookMode string) error {
	if hookMode == "strict" {
		return nil
	}
	return writeSettingsLocal(worktreePath, hookModeTemplates[hookMode])
}

func writeSettingsLocal(worktreePath, content string) error {
	claudeDir := filepath.Join(worktreePath, ".claude")
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return fmt.Errorf("creating .claude dir: %w", err)
	}
	path := filepath.Join(claudeDir, "settings.local.json")
	existing, _ := os.ReadFile(path)
	if bytes.Equal(existing, []byte(content)) {
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("writing settings.local.json: %w", err)
	}
	return nil
}

// deployHookScripts writes hook scripts and env wrapper to .claude/hooks/.
func deployHookScripts(targetPath string, scripts HookScripts) error {
	hooksDir := filepath.Join(targetPath, ".claude", "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("creating hooks dir: %w", err)
	}
	files := map[string][]byte{
		"path-guard.sh":        scripts.PathGuard,
		"bash-firewall.sh":     scripts.BashFirewall,
		"git-guard.sh":         scripts.GitGuard,
		"zpit-env.cmd":         scripts.EnvWrapper,
		"zpit-env.ps1":         scripts.EnvWrapperPS1,
		"zpit-exit.cmd":        scripts.ExitWrapper,
		"zpit-exit.ps1":        scripts.ExitWrapperPS1,
		"notify-permission.sh": scripts.NotifyPermission,
		"worktree-create.sh":   scripts.WorktreeCreate,
	}
	for name, content := range files {
		p := filepath.Join(hooksDir, name)
		if err := os.WriteFile(p, content, 0o755); err != nil {
			return fmt.Errorf("writing %s: %w", name, err)
		}
	}
	return nil
}

// mergeSettingsHooks reads existing .claude/settings.json, sets the "hooks" key
// based on hookMode, and writes back. Preserves all other existing keys.
// hookMode is assumed already validated.
func mergeSettingsHooks(targetPath, hookMode string) error {
	claudeDir := filepath.Join(targetPath, ".claude")
	if err := os.MkdirAll(claudeDir, 0o755); err != nil {
		return fmt.Errorf("creating .claude dir: %w", err)
	}
	settingsPath := filepath.Join(claudeDir, "settings.json")

	// Read existing settings or start fresh.
	var settings map[string]interface{}
	data, err := os.ReadFile(settingsPath)
	if err == nil {
		if err := json.Unmarshal(data, &settings); err != nil {
			settings = make(map[string]interface{})
		}
	} else {
		settings = make(map[string]interface{})
	}

	// Extract "hooks" value from the mode template.
	var parsed map[string]interface{}
	if err := json.Unmarshal([]byte(hookModeTemplates[hookMode]), &parsed); err != nil {
		return fmt.Errorf("parsing hook template: %w", err)
	}
	settings["hooks"] = parsed["hooks"]

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling settings: %w", err)
	}
	newData := append(out, '\n')
	if bytes.Equal(data, newData) {
		return nil
	}
	return os.WriteFile(settingsPath, newData, 0o644)
}

// CleanSettingsHooks removes the Zpit-injected "hooks" key from .claude/settings.json.
// If the file becomes an empty object after removal, it is deleted.
// Returns true if any change was made.
func CleanSettingsHooks(projectPath string) bool {
	settingsPath := filepath.Join(projectPath, ".claude", "settings.json")
	data, err := os.ReadFile(settingsPath)
	if err != nil {
		return false
	}

	var settings map[string]interface{}
	if err := json.Unmarshal(data, &settings); err != nil {
		return false
	}
	if _, ok := settings["hooks"]; !ok {
		return false
	}

	delete(settings, "hooks")

	if len(settings) == 0 {
		os.Remove(settingsPath)
		return true
	}

	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return false
	}
	os.WriteFile(settingsPath, append(out, '\n'), 0o644)
	return true
}
